### ISSUE TITLE
[Player] Task list

### ISSUE THREAD

**Issue by sergeifedorenko** [easably/RoadMap#16]
- [x]  new icon for application
![icon128](https://user-images.githubusercontent.com/5947223/79880416-a87b4380-83f8-11ea-8f40-bb79b33066ad.png)
- [x] Every word need (instead "Word repeat games" need "Word Repeat Games"
![image](https://user-images.githubusercontent.com/5947223/79880703-0871ea00-83f9-11ea-8a92-5cfc55b56d3a.png)
- [ ]  need the [same design](https://www.figma.com/file/TnmHxzHWnAFhNbT5UhG0dh/%D0%9F%D0%BB%D0%B5%D0%B5%D1%80-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D1%82%D0%B8%D0%BF?node-id=301%3A15744) 
![image](https://user-images.githubusercontent.com/5947223/79881550-052b2e00-83fa-11ea-9d64-60958fa71690.png)
@annamaksimik maybe we need a dark design 

- [ ] we need preselected native language in the filter
![image](https://user-images.githubusercontent.com/5947223/79881855-6a7f1f00-83fa-11ea-9d0f-a08905c3bd90.png)

- [x] we need English titles 
![image](https://user-images.githubusercontent.com/5947223/79881899-7cf95880-83fa-11ea-8c7b-d5ef20fcd5f1.png)

- [ ] change text "Download by TED’s URL"
- [ ] we need new icon 
![image](https://user-images.githubusercontent.com/5947223/79882411-3d7f3c00-83fb-11ea-8625-b01c0fba031c.png)
- [x] change the name of the video, which is saved to tutor
![12](https://user-images.githubusercontent.com/63041847/79975686-0d3fa800-84a4-11ea-9e6d-b70e72c9cdd2.jpg)

@annamaksimik help to find the "Enter" icon

**Comment by annamaksimik** [comment]
**Dark design** -  https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/EasyLang_Player?node-id=12%3A154

**Comment by annamaksimik** [comment]
**Word Repeat Games** - https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/EasyLang_Player?node-id=12%3A87

**Comment by annamaksimik** [comment]
**Settings** - https://www.figma.com/file/U9Hnshg4GcuJzDkyBI9Zqj/EasyLang_Player?node-id=1%3A2

**Comment by pavladan** [comment]
> we need preselected native language in the filter

I removed the filter. Languages taken from settings

**Comment by pavladan** [comment]
> change text "Download by TED’s URL"
we need new icon

This is incorrect because the video does not download

**Comment by pavladan** [comment]
> need the [same design](https://www.figma.com/file/TnmHxzHWnAFhNbT5UhG0dh/%D0%9F%D0%BB%D0%B5%D0%B5%D1%80-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D1%82%D0%B8%D0%BF?node-id=301%3A15744)

This design does't take into indents and  social networks auth

**Comment by pavladan** [comment]
Done in [0.8.81](https://github.com/easably/platform-player-extension/releases/tag/0.8.81)
