### ISSUE TITLE
[UI Tutor] Task List

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/RoadMap#18]
- [ ] delete the raw "написать разработчикам"
- [ ] change inscription "Version 0.3.13" to "v.0.3.13"
![9](https://user-images.githubusercontent.com/63041847/79967965-322e1e00-8498-11ea-95ac-f1b09ae94127.jpg)
- [ ] progress bar has different size in 2 games without using it
![950440BF-7AE5-4A9B-8402-767B414324CE](https://user-images.githubusercontent.com/63041847/79977864-a623f280-84a7-11ea-9d53-0082f58a10a3.jpeg)
![7EE2E364-44F0-4F7D-A496-14EAE761C0EF](https://user-images.githubusercontent.com/63041847/79977883-ae7c2d80-84a7-11ea-9a76-b489a02614f5.jpeg)

MOBILE VERSION 
- [ ] the name of the lesson isn’t displayed in the header ( iPhone 7)
![26480A18-2E0A-478F-8BCC-BB26DFAEFD9A](https://user-images.githubusercontent.com/63041847/79978948-6c53eb80-84a9-11ea-91bd-d6d5545259c1.jpeg)

- [ ] the bottom line shifted in the game
![31291911-16EA-4006-A357-4A7B7274CC71](https://user-images.githubusercontent.com/63041847/79979244-e3897f80-84a9-11ea-8a41-38345b8793de.jpeg)

- [ ] in the horizontal position of mobile phone the bottom line shifted in the game 
![2B8DD69C-335B-41B4-A318-C2222356CE85](https://user-images.githubusercontent.com/63041847/79979486-411dcc00-84aa-11ea-907d-37ff66d186ac.jpeg)

@Vlad-CSA
