### ISSUE TITLE
[UI extension] Task List

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/RoadMap#19]
- [ ] warning about limit isn't displayed when a user isn't logged in to tutor.

- [ ] when we change language in extension english to english, and highlight the whole sentence or paragraph- the whole text appear
![image](https://user-images.githubusercontent.com/63041847/79985435-43d0ef00-84b3-11ea-8e72-d47683699fd8.png)

- [ ] limit warning appeared when a paragraph was chosen
(when multiple words are chosen one save click counts as multiple saves. Therefore, a saving limit is immediately reached. )  
![14](https://user-images.githubusercontent.com/63041847/79985718-b510a200-84b3-11ea-8cf1-a824a167ffa0.png)

- [ ] in extension when link "web tutor" is clicked with right mousebuttom, appear strange link 
![15](https://user-images.githubusercontent.com/63041847/79985956-002ab500-84b4-11ea-8802-884e6f9f7bb6.png)
@Vlad-CSA 

- [ ] add web started page extension for Player
![11](https://user-images.githubusercontent.com/63041847/79970152-2c860780-849b-11ea-83b1-1cba8b02efea.jpg)

- [ ] explain on these pages the inability to save the whole paragraph to tutor (according to some cust dev's some people decided that they can save the whole paragraph to learn the word in the contex)

- [ ] Sign in duplication. If you log in un extension, what for do it again in player.

- [ ] Unclear extension download. It's difficult for people to understand where the extentsion was saved. 

- [ ] Word save to tutor is unclear. The displayed window at the top of the page gives insufficient information where the word has been saved

- [ ] Emphasize that there are no viruses.

- [ ] when switching sign up to sign in and vice versa you need to reenter the data. It should be constantly stay
![15](https://user-images.githubusercontent.com/63041847/80089655-ef874700-8566-11ea-9280-30080426745a.jpg)
![16](https://user-images.githubusercontent.com/63041847/80089688-fc0b9f80-8566-11ea-8b75-91955bcf2d4a.jpg)

- [ ] Like the previous item, switching is not clearly shown. (Sign in-Sign up)
