### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/RoadMap#49]
- [x] Add bullet list from "Read and learn" to "Watch and learn"
- [x] remove "free start" from " Watch and learn"
- [x] when we tap on the main page in Russian: "Start free"- the english page appears.
